### ISSUE TITLE
Screenshot overview of all possible input types

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp-doc#110]
We have loads of Input types, and they're all described in text (only a few have pages containing images of how they look). Nice would be to make the input type "root" page list all inputs with a screenshot of how they look.

Suggestion came during training developers that struggled with grasping what all the types did without having to read loads of text and doing a lot of clicking and back tracking.

Here's how the ACF-plugin for Wordpress does it. You go to their docs and click "Available types" basically, and then you get this handy overview. Click it to get into details for that particular type.
![screen shot 2018-10-05 at 15 27 26](https://user-images.githubusercontent.com/1465598/46538441-56c1a580-c8b4-11e8-95ee-ce9cca5e7f40.png)

**Comment by jsi** [comment]
The new input types doc for 7.0 has screenshots of each input type except the custom selector: https://developer.enonic.com/docs/xp/stable/cms/input-types

That solves this issue.
