### ISSUE TITLE
Create documentation on general JVM configuration

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/xp-doc#40]
We should have a section with recommended JVM-configuration:
* heapsize
* gc-settings
* troubleshooting? gc-logging, heap-dump etc

**Comment by sigdestad** [comment]
This should also comment on differences if a node has ES data or not (i.e. a pure app engine vs data vs _all_ nodes)

**Comment by jsi** [comment]
+1

**Comment by jsi** [comment]
Moved to and transformed a little here : enonic/doc-xp#94
