### ISSUE TITLE
Document the "hidden" input type "ContentTypeFilter"

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/xp-doc#41]
It is possible to create a input type of ContentTypeFilter in any schema, that will list all active/installed content types for any installation. This is however not documented, but apps like the RSS feed app and the Sitemap.xml app depends on this feature. It should be documented.

**Comment by sigdestad** [comment]
You should be able to use customSelector and the Content API I guess? Or maybe the content API does not provide what you need?
‌


https://enonic.com <https://enonic.com/> - A web operating system for your sites and applications

**Comment by Bellfalasch** [comment]
That's for the future versions of the app. For the last year or so they've been using ContentTypeFilter but that is not documented. Should be documented.

**Comment by aro** [comment]
The content API supports it now, it didn't until 6.10
Now it's possible to create a CustomSelector.

http://repo.enonic.com/public/com/enonic/xp/docs/6.10.0/docs-6.10.0-libdoc.zip!/module-content.html#.getTypes

**Comment by sigdestad** [comment]
I guess the GetTypes function should support a site parameter (or context true/false) so it would only return the types available in the context?

Vennlig hilsen/Best regards 

Thomas Sigdestad
CTO & Co-Founder
+47 98236011

https://enonic.com - A web operating system for your sites and applications

**Comment by Bellfalasch** [comment]
Nice ideas guys, but totally off topic =)

I'm just saying that XP has a input type - ContentTypeFilter - that at least 2 apps on the Market are using but it is not documented anywhere by us. So we should document it =)

**Comment by aro** [comment]
See enonic/xp/issues/5412
